In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.decomposition import PCA
from sklearn.ensemble import IsolationForest
import joblib
import os
os.chdir('Resources/')

In [ ]:
df = pd.read_csv('4_Encrypted_Data.csv')
df.head()

,Age,Sex,ChestPainType,RestingBloodPressure,Cholesterol,FastingBloodSugar,RestingECG,MaximumHeartRate,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,0,0,0,0,0,0,0,0,0,0,0,0
1,2739517856553132910837996140463046561002056734878,5855621056848202200152943217350522901513916747947,2437545241045016679266925293322878865310766273...,1079614743916430358857457421765540466317825368...,235401055051756973300637270984945453108665663101,0,0,1163500389636828390742332666769595043402774777...,0,1731293662809263711557680077912500755732452491...,3014189590008081827318830704138344439007056773399,1
2,3951027072433918461194237321151036802876241396...,0,0,3503657895357580763960593572950538050884851551...,4588008049114976517533414594745897088194686237...,0,2107320569395791004782254548085452927399281613...,3528395727645342758185262373692017841246403281...,0,0,0,0
3,3015381903922016617085975666464524260059236838...,5855621056848202200152943217350522901513916747947,2986960489035147079323615035059065546236357181...,5990529079441484063867435974748605261778747110...,5869232556038830509582305305314685363708773238...,0,0,6983980600516377299933482088412314615234638980...,1567772662659414360042140982786078507847258681...,1068517114155727546501006609047526049273597305...,3014189590008081827318830704138344439007056773399,1
4,8902537892663436948774199186438245066306729535...,0,2437545241045016679266925293322878865310766273...,5475913473935986861430190578928984101085671982...,9600691522698155411149937690938190741403235282276,0,0,3233301625726655004705667351250352466171561134...,0,0,0,0

In [ ]:
imputer = SimpleImputer(strategy='mean')
df_imputed = pd.DataFrame(imputer.fit_transform(df), columns=df.columns)
df_imputed

,Age,Sex,ChestPainType,RestingBloodPressure,Cholesterol,FastingBloodSugar,RestingECG,MaximumHeartRate,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0
1,2.739518e+48,5.855621e+48,2.437545e+49,1.079615e+49,2.354011e+47,0.0,0.000000e+00,1.163500e+49,0.000000e+00,1.731294e+49,3.014190e+48,1.0
2,3.951027e+49,0.000000e+00,0.000000e+00,3.503658e+49,4.588008e+49,0.0,2.107321e+49,3.528396e+49,0.000000e+00,0.000000e+00,0.000000e+00,0.0
3,3.015382e+49,5.855621e+48,2.986960e+49,5.990529e+49,5.869233e+49,0.0,0.000000e+00,6.983981e+49,1.567773e+49,1.068517e+49,3.014190e+48,1.0
4,8.902538e+49,0.000000e+00,2.437545e+49,5.475913e+49,9.600692e+48,0.0,0.000000e+00,3.233302e+49,0.000000e+00,0.000000e+00,0.000000e+00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
4039,1.810475e+50,5.855621e+48,2.437545e+49,1.591215e+48,2.050007e+50,0.0,0.000000e+00,6.028786e+50,0.000000e+00,1.068517e+49,3.014190e+48,1.0
4040,7.618569e+49,5.855621e+48,2.437545e+49,1.298956e+50,1.200856e+51,0.0,2.107321e+49,4.861357e+50,0.000000e+00,7.506680e+50,3.014190e+48,1.0
4041,2.855765e+48,0.000000e+00,5.067233e+49,1.400678e+50,1.777178e+51,0.0,2.107321e+49,8.220719e+50,1.567773e+49,0.000000e+00,2.236568e+49,0.0
4042,1.136709e+50,0.000000e+00,2.986960e+49,1.079615e+49,9.593369e+49,0.0,0.000000e+00,1.108936e+50,0.000000e+00,0.000000e+00,2.236568e+49,0.0
4043,8.902538e+49,0.000000e+00,5.067233e+49,1.591215e+48,2.489554e+50,0.0,2.107321e+49,7.133089e+50,0.000000e+00,7.975971e+49,3.014190e+48,0.0

In [ ]:
X = df_imputed.drop(['HeartDisease'], axis='columns')
X

,Age,Sex,ChestPainType,RestingBloodPressure,Cholesterol,FastingBloodSugar,RestingECG,MaximumHeartRate,ExerciseAngina,Oldpeak,ST_Slope
0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
1,2.739518e+48,5.855621e+48,2.437545e+49,1.079615e+49,2.354011e+47,0.0,0.000000e+00,1.163500e+49,0.000000e+00,1.731294e+49,3.014190e+48
2,3.951027e+49,0.000000e+00,0.000000e+00,3.503658e+49,4.588008e+49,0.0,2.107321e+49,3.528396e+49,0.000000e+00,0.000000e+00,0.000000e+00
3,3.015382e+49,5.855621e+48,2.986960e+49,5.990529e+49,5.869233e+49,0.0,0.000000e+00,6.983981e+49,1.567773e+49,1.068517e+49,3.014190e+48
4,8.902538e+49,0.000000e+00,2.437545e+49,5.475913e+49,9.600692e+48,0.0,0.000000e+00,3.233302e+49,0.000000e+00,0.000000e+00,0.000000e+00
...,...,...,...,...,...,...,...,...,...,...,...
4039,1.810475e+50,5.855621e+48,2.437545e+49,1.591215e+48,2.050007e+50,0.0,0.000000e+00,6.028786e+50,0.000000e+00,1.068517e+49,3.014190e+48
4040,7.618569e+49,5.855621e+48,2.437545e+49,1.298956e+50,1.200856e+51,0.0,2.107321e+49,4.861357e+50,0.000000e+00,7.506680e+50,3.014190e+48
4041,2.855765e+48,0.000000e+00,5.067233e+49,1.400678e+50,1.777178e+51,0.0,2.107321e+49,8.220719e+50,1.567773e+49,0.000000e+00,2.236568e+49
4042,1.136709e+50,0.000000e+00,2.986960e+49,1.079615e+49,9.593369e+49,0.0,0.000000e+00,1.108936e+50,0.000000e+00,0.000000e+00,2.236568e+49
4043,8.902538e+49,0.000000e+00,5.067233e+49,1.591215e+48,2.489554e+50,0.0,2.107321e+49,7.133089e+50,0.000000e+00,7.975971e+49,3.014190e+48

In [ ]:
Y = df[['HeartDisease']]
Y

      HeartDisease
0                0
1                1
2                0
3                1
4                0
...            ...
4039             1
4040             1
4041             0
4042             0
4043             0

[4044 rows x 1 columns]

In [ ]:
scaler = StandardScaler()
df_scaled = pd.DataFrame(scaler.fit_transform(X), columns=X.columns)
df_scaled

,Age,Sex,ChestPainType,RestingBloodPressure,Cholesterol,FastingBloodSugar,RestingECG,MaximumHeartRate,ExerciseAngina,Oldpeak,ST_Slope
0,-0.883095,-0.574685,-1.664860,-0.666317,-0.974477,-0.520882,-0.832005,-1.049723,-0.826579,-0.624456,-0.784328
1,-0.873713,1.740083,-0.202199,-0.643791,-0.974354,-0.520882,-0.832005,-1.031571,-0.826579,-0.567027,-0.409761
2,-0.747775,-0.574685,-1.664860,-0.593213,-0.950471,-0.520882,0.403826,-0.994676,-0.826579,-0.624456,-0.784328
3,-0.779821,1.740083,0.127481,-0.541325,-0.943767,-0.520882,-0.832005,-0.940764,1.226487,-0.589012,-0.409761
4,-0.578189,-0.574685,-0.202199,-0.552062,-0.969454,-0.520882,-0.832005,-0.999280,-0.826579,-0.624456,-0.784328
...,...,...,...,...,...,...,...,...,...,...,...
4039,-0.263020,1.740083,-0.202199,-0.662997,-0.867214,-0.520882,-0.832005,-0.109156,-0.826579,-0.589012,-0.409761
4040,-0.622164,1.740083,-0.202199,-0.395291,-0.346149,-0.520882,0.403826,-0.291290,-0.826579,1.865589,-0.409761
4041,-0.873315,-0.574685,1.375759,-0.374067,-0.044599,-0.520882,0.403826,0.232813,1.226487,-0.624456,1.995010
4042,-0.493780,-0.574685,0.127481,-0.643791,-0.924282,-0.520882,-0.832005,-0.876715,-0.826579,-0.624456,1.995010
4043,-0.578189,-0.574685,1.375759,-0.662997,-0.844215,-0.520882,0.403826,0.063129,-0.826579,-0.359885,-0.409761

In [ ]:
df_scaled = pd.concat([df_scaled, Y], axis=1)
df_scaled.to_csv('6_Preprocessed_Data.csv', index=False)

In [ ]:
joblib.dump(scaler, '6_Scaler.joblib')

['6_Scaler.joblib']